services:
  fastfood:
    container_name: fastfood
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080" 
    environment:
      DB_URL: jdbc:postgresql://db_fastfood:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - db_fastfood
  db_fastfood:
    container_name: db_fastfood
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
